/*

ASSIGNMENT RULES

– All the answers must be written in JavaScript

– You can ask for help, reach the Teaching Assistants if needed

– You can Google / use StackOverflow BUT only when you think you need something we didn’t cover during lessons yet

– You can test your code in a separate file or de-commenting the single exercises in this one.

– You can use the bash terminal, the VSCode terminal or the one embedded in your Operating System if you’re using macOS or Linux.

– Complete as many exercises as you can

*/

function titleCreator(titleText, titleSymbol) {
  console.log(
    `\n${titleSymbol}${titleSymbol}${titleSymbol}${titleSymbol}${titleSymbol}${titleSymbol}${titleText}${titleSymbol}${titleSymbol}${titleSymbol}${titleSymbol}${titleSymbol}${titleSymbol}\n`
  );
}

// JS Basics

titleCreator("JAVASCRIPT BASICS", "---");

/* EXERCISE A

Create a variable called test and assign a string value to it.

*/

titleCreator("EXERCISE A", "---");

let test = "This is the string value of the variable named 'test'.";
console.log(test);

/* EXERCISE B

Create a variable called sum and assign to it the result of the sum between the numbers 10 and 20.

*/

titleCreator("EXERCISE B", "---");

let sum = 0;

for (let i = 10; i <= 20; i++) {
  sum += i;
}

console.log(
  `The sum of the numbers between 10(included) and 20(included) is ${sum}`
);

/* EXERCISE C

Create a variable called random and assign to it a random number between 0 and 20 (it should be randomly created at each execution).

*/

titleCreator("EXERCISE C", "---");

random = parseInt(Math.random() * 20);

console.log(`The random number generated by the computer is ${random}`);

/* EXERCISE D

Create a variable called me and assign to it an object containing the following information: name = your name, surname = your surname, age = your age.

*/

titleCreator("EXERCISE D", "---");

let me = {
  name: "Muhammed Yasir",
  surname: "Ozdemir",
  age: 20,
};

console.log("General information about me:", me);

/* EXERCISE E

Write a piece of code for programmatically removing the age property from the previously create object.

*/

titleCreator("EXERCISE E", "---");

delete me.age;

console.log("Age property of the object named me is deleted:", me);

/* EXERCISE F

Write a piece of code for programmatically adding to the me object you defined before an array called skills, containing the programming languages you know right now.

*/

titleCreator("EXERCISE F", "---");

me.skills = ["HTML", "CSS", "Javascript", "Java"];

console.log("Skills property added to the object named me:", me);

/* EXERCISE G

Write a piece of code for programmatically removing the last skill from the skills array inside the me object.

*/

titleCreator("EXERCISE G", "---");

me.skills.pop();

console.log("The last skill removed:", me.skills);

// JS Functions

titleCreator("JAVASCRIPT FUNCTIONS", "---");

/* EXERCISE 1

Write a function called dice; it should randomize an integer number between 1 and 6.

*/

titleCreator("EXERCISE 1", "---");

function dice() {
  return (random = parseInt(Math.random() * 6 + 1));
}

console.log("The number created by the dice function is:", dice());

/* EXERCISE 2

Write a function called whoIsBigger which receives 2 numbers as parameters and returns the biggest one.

*/

titleCreator("EXERCISE 2", "---");

function whoIsBigger(n1, n2) {
  let biggest;
  if (n1 > n2) {
    biggest = n1;
    console.log("The biggest one is:", n1);
  } else {
    biggest = n2;
    console.log("The biggest one is:", n2);
  }
  return biggest;
}

whoIsBigger(9, 7);

/* EXERCISE 3

Write a function called splitMe which receives a string as a parameter and returns an array with every word in that string.

Ex.: splitMe("I love coding") => returns ["I", "Love", "Coding"]

*/

titleCreator("EXERCISE 3", "---");

function splitMe(string) {
  let wordsArray = string.split(" ");
  console.log(wordsArray);
}
splitMe("I wanna get lost with you");

/* EXERCISE 4

Write a function called deleteOne which receives a string and a boolean as parameters.

If the boolean value is true it should return the string without the first letter, otherwise it should remove the last one from it.

*/

titleCreator("EXERCISE 4", "---");

function deleteOne(string, boolean) {
  if (boolean) {
    console.log(string.slice(1));
  } else {
    delete string.charAt(-1);
    console.log(string.slice(0, -1));
  }
}

deleteOne("Hello world", false);

/* EXERCISE 5

Write a function called onlyLetters which receives a string as a parameter and returns it removing all the digits.

Ex.: onlyLetters("I have 4 dogs") => returns "I have dogs"

*/

titleCreator("EXERCISE 5", "---");

function onlyLetters(string) {
  let stringWithoutDigits = string.replace(/[0-9]/g, ""); // NOTE to myself: if NaN can be used as well. :)
  console.log(stringWithoutDigits);
}

onlyLetters("I have 4 dogs");

/* EXERCISE 6

Write a function called isThisAnEmail which receives a string as a parameter and returns true if the string is a valid email address.

*/

titleCreator("EXERCISE 6", "---");

function isThisAnEmail(string) {
  if (
    string.match(
      /^(([^<>()[\]\\.,;:\s@"]+(\.[^<>()[\]\\.,;:\s@"]+)*)|(".+"))@((\[[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\])|(([a-zA-Z\-0-9]+\.)+[a-zA-Z]{2,}))$/
    )
  ) {
    console.log("This is a valid email");
  } else {
    console.log("This is not a valid email");
  }
}

isThisAnEmail("yasirozdmr@yandex.com");

/* EXERCISE 7

Write a function called whatDayIsIt that should return the current day of the week.

*/

titleCreator("EXERCISE 7", "---");

function whatDayIsIt() {
  let days = [
    "Sunday",
    "Monday",
    "Tuesday",
    "Wednesday",
    "Thursday",
    "Friday",
    "Saturday",
  ];
  let today = new Date(); // date info is provided by the computer itself
  let currentDayOfTheWeek = days[today.getDay()];
  console.log(currentDayOfTheWeek);
}

whatDayIsIt();

/* EXERCISE 8

Write a function called rollTheDices which receives a number as a parameter.

It should invoke the dice() function defined in Ex1 the specified amount of times,

and return an object containing a sum property holding the sum of all values extracted

and a values array containing the single values of the dice rolls themselves.

Example: RollTheDices(3) => returns {

sum: 10

values: [3, 3, 4]

}

*/

titleCreator("EXERCISE 8", "---");

function rollTheDices(number) {
  let diceRolls = [];
  let sumOfAllValues = 0;
  for (i = 0; i < number; i++) {
    diceRolls[i] = dice();
    sumOfAllValues += diceRolls[i];
  }
  console.log("The dice rolls:", diceRolls);
  console.log("\nThe sum of dice rolls:", sumOfAllValues);

  return (object = {
    diceRolls,
    sumOfAllValues,
  });
}

rollTheDices(4);

/* EXERCISE 9

Write a function called howManyDays which receives a date as a parameter and returns the number of days passed since that date.

*/

titleCreator("EXERCISE 9", "---");

function howManyDays(date) {
  let today = new Date(date.getTime());
  let past = new Date(date.getFullYear(), 0, 1);
  return Math.ceil((today - past + 1) / 86400000);
}

console.log(howManyDays(new Date(2022, 12, 2)));

/* EXERCISE 10

Write a function called isTodayMyBirthday which should return true if today’s your birthday, false otherwise.

*/

titleCreator("EXERCISE 10", "---");

function isTodayMyBirthday() {
  let today = new Date();
  let month = today.getMonth() + 1; //months are starting from 0, that's why we should add 1 to the month info
  let day = today.getDate();

  let birthdayCheck = month === 6 && day === 2 ? true : false;

  if (birthdayCheck) {
    console.log("Today is your birthday. HAPPY BIRTHDAY!");
  } else {
    console.log("Unfortunately, today is not your birthday.");
  }
}

isTodayMyBirthday();

// JS Arrays & Objects

titleCreator("JAVASCRIPT ARRAYS AND OBJECTS", "---");

const movies = [
  {
    Title: "The Lord of the Rings: The Fellowship of the Ring",

    Year: "2001",

    imdbID: "tt0120737",

    Type: "movie",

    Poster:
      "https://m.media-amazon.com/images/M/MV5BN2EyZjM3NzUtNWUzMi00MTgxLWI0NTctMzY4M2VlOTdjZWRiXkEyXkFqcGdeQXVyNDUzOTQ5MjY@._V1_SX300.jpg",
  },

  {
    Title: "The Lord of the Rings: The Return of the King",

    Year: "2003",

    imdbID: "tt0167260",

    Type: "movie",

    Poster:
      "https://m.media-amazon.com/images/M/MV5BNzA5ZDNlZWMtM2NhNS00NDJjLTk4NDItYTRmY2EwMWZlMTY3XkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_SX300.jpg",
  },

  {
    Title: "The Lord of the Rings: The Two Towers",

    Year: "2002",

    imdbID: "tt0167261",

    Type: "movie",

    Poster:
      "https://m.media-amazon.com/images/M/MV5BNGE5MzIyNTAtNWFlMC00NDA2LWJiMjItMjc4Yjg1OWM5NzhhXkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_SX300.jpg",
  },

  {
    Title: "Lord of War",

    Year: "2005",

    imdbID: "tt0399295",

    Type: "movie",

    Poster:
      "https://m.media-amazon.com/images/M/MV5BMTYzZWE3MDAtZjZkMi00MzhlLTlhZDUtNmI2Zjg3OWVlZWI0XkEyXkFqcGdeQXVyNDk3NzU2MTQ@._V1_SX300.jpg",
  },

  {
    Title: "Lords of Dogtown",

    Year: "2005",

    imdbID: "tt0355702",

    Type: "movie",

    Poster:
      "https://m.media-amazon.com/images/M/MV5BNDBhNGJlOTAtM2ExNi00NmEzLWFmZTQtYTZhYTRlNjJjODhmXkEyXkFqcGdeQXVyNDk3NzU2MTQ@._V1_SX300.jpg",
  },

  {
    Title: "The Lord of the Rings",

    Year: "1978",

    imdbID: "tt0077869",

    Type: "movie",

    Poster:
      "https://m.media-amazon.com/images/M/MV5BOGMyNWJhZmYtNGQxYi00Y2ZjLWJmNjktNTgzZWJjOTg4YjM3L2ltYWdlXkEyXkFqcGdeQXVyNTAyODkwOQ@@._V1_SX300.jpg",
  },

  {
    Title: "Lord of the Flies",

    Year: "1990",

    imdbID: "tt0100054",

    Type: "movie",

    Poster:
      "https://m.media-amazon.com/images/M/MV5BOTI2NTQyODk0M15BMl5BanBnXkFtZTcwNTQ3NDk0NA@@._V1_SX300.jpg",
  },

  {
    Title: "The Lords of Salem",

    Year: "2012",

    imdbID: "tt1731697",

    Type: "movie",

    Poster:
      "https://m.media-amazon.com/images/M/MV5BMjA2NTc5Njc4MV5BMl5BanBnXkFtZTcwNTYzMTcwOQ@@._V1_SX300.jpg",
  },

  {
    Title: "Greystoke: The Legend of Tarzan, Lord of the Apes",

    Year: "1984",

    imdbID: "tt0087365",

    Type: "movie",

    Poster:
      "https://m.media-amazon.com/images/M/MV5BMTM5MzcwOTg4MF5BMl5BanBnXkFtZTgwOTQwMzQxMDE@._V1_SX300.jpg",
  },

  {
    Title: "Lord of the Flies",

    Year: "1963",

    imdbID: "tt0057261",

    Type: "movie",

    Poster:
      "https://m.media-amazon.com/images/M/MV5BOGEwYTlhMTgtODBlNC00ZjgzLTk1ZmEtNmNkMTEwYTZiM2Y0XkEyXkFqcGdeQXVyMzU4Nzk4MDI@._V1_SX300.jpg",
  },

  {
    Title: "The Avengers",

    Year: "2012",

    imdbID: "tt0848228",

    Type: "movie",

    Poster:
      "https://m.media-amazon.com/images/M/MV5BNDYxNjQyMjAtNTdiOS00NGYwLWFmNTAtNThmYjU5ZGI2YTI1XkEyXkFqcGdeQXVyMTMxODk2OTU@._V1_SX300.jpg",
  },

  {
    Title: "Avengers: Infinity War",

    Year: "2018",

    imdbID: "tt4154756",

    Type: "movie",

    Poster:
      "https://m.media-amazon.com/images/M/MV5BMjMxNjY2MDU1OV5BMl5BanBnXkFtZTgwNzY1MTUwNTM@._V1_SX300.jpg",
  },

  {
    Title: "Avengers: Age of Ultron",

    Year: "2015",

    imdbID: "tt2395427",

    Type: "movie",

    Poster:
      "https://m.media-amazon.com/images/M/MV5BMTM4OGJmNWMtOTM4Ni00NTE3LTg3MDItZmQxYjc4N2JhNmUxXkEyXkFqcGdeQXVyNTgzMDMzMTg@._V1_SX300.jpg",
  },

  {
    Title: "Avengers: Endgame",

    Year: "2019",

    imdbID: "tt4154796",

    Type: "movie",

    Poster:
      "https://m.media-amazon.com/images/M/MV5BMTc5MDE2ODcwNV5BMl5BanBnXkFtZTgwMzI2NzQ2NzM@._V1_SX300.jpg",
  },
];

/* EXERCISE 11

Write a function called deleteProp which receives an object and a string as parameters,

and returns the given object after deleting its property named as the given string.

*/

titleCreator("EXERCISE 11", "---");

function deleteProp(object, string) {
  console.log("Before deleting:", object);
  delete object[string];
  console.log("\n After deleting:", object);
}

deleteProp(movies[0], "imdbID");

/* EXERCISE 12

Write a function called oldestMovie which finds the oldest movie in the provided movies array.

*/

titleCreator("EXERCISE 12", "---");

function oldestMovie(array) {
  let oldestMovieHolder = 2023;
  for (let i = 0; i < array.length; i++) {
    if (array[i].Year < oldestMovieHolder) {
      oldestMovieHolder = array[i].Year;
      oldestMovie = array[i];
    }
  }
  console.log(oldestMovie);
}

oldestMovie(movies);

/* EXERCISE 13

Write a function called countMovies which returns the number of movies contained in the provided movies array.

*/

titleCreator("EXERCISE 13", "---");

function countMovies(array) {
  return (numberOfMovies = array.length);
}

console.log("There are", countMovies(movies), "movies available.");

/* EXERCISE 14

Write a function called onlyTheTitles which creates an array with just the titles of the movies contained in the provided movies array.

*/

titleCreator("EXERCISE 14", "---");

function onlyTheTitles(array) {
  let titleHolderArray = [];
  for (let i = 0; i < array.length; i++) {
    titleHolderArray[i] = array[i].Title;
  }
  return titleHolderArray;
}

console.log("Titles of the movies are:", onlyTheTitles(movies));

/* EXERCISE 15

Write a function called onlyInThisMillennium which returns only the movies produced in this millennium from the provided movies array.

*/

titleCreator("EXERCISE 15", "---");

function onlyInThisMillennium(array) {
  let onlyInThisMillenniumArray = [];
  for (i = 0; i < array.length; i++) {
    if (array[i].Year >= 2000) {
      onlyInThisMillenniumArray[i] = array[i];
    }
  }
  return onlyInThisMillenniumArray;
}

console.log("Movies that are produced in this millennium:\n");

console.log(onlyInThisMillennium(movies));

/* EXERCISE 16

Write a function called getMovieById which receives an id as a parameter and returns the movie with the given id from the provided movies array.

*/

titleCreator("EXERCISE 16", "---");

function getMovieById(string) {
  let theMovieThatYouAreLookingFor;
  for (let i = 0; i < movies.length; i++) {
    if (movies[i].imdbID === string) {
      return (theMovieThatYouAreLookingFor = movies[i]);
    }
  }
}

console.log("The movie that you are looking for:", getMovieById("tt0399295"));

/* EXERCISE 17

Write a function called sumAllTheYears which returns the sum of all the years in which the movies in the provided movies array have been produced.

*/

titleCreator("EXERCISE 17", "---");

function sumAllTheYears(array) {
  let sumOfYears = 0;
  for (let i = 0; i < array.length; i++) {
    sumOfYears += parseInt(array[i].Year);
  }
  console.log(
    "The sum of all the years that represent movies production year is:",
    sumOfYears
  );
}

sumAllTheYears(movies);

/* EXERCISE 18

Write a function called searchByTitle which receives a string as a parameter and returns all the movies in the provided movies array which contain that string in the title.

*/

titleCreator("EXERCISE 18", "---");

function searchByTitle(string) {
  let theMovieThatYouAreLookingFor;
  for (let i = 0; i < movies.length; i++) {
    if (movies[i].Title === string) {
      return (theMovieThatYouAreLookingFor = movies[i]);
    }
  }
}

console.log(searchByTitle("Avengers: Endgame"));

/* EXERCISE 19

Write a function called searchAndDivide which receives a string as a parameter and returns an object;

this object should contain an array called match, made by all the movies from the provided movies array which contain the given string in the title,

and another array unmatch with all the remaining ones.

*/

titleCreator("EXERCISE 19", "---");

function searchAndDivide(string) {
  let match = [];
  let unmatch = [];

  for (let i = 0; i < movies.length; i++) {
    let title = movies[i].Title.toLowerCase();

    let isInclude = title.includes(string.toLowerCase()) ? true : false;

    if (isInclude) {
      match.push(movies[i]);
    } else {
      unmatch.push(movies[i]);
    }
  }

  console.log("-----------MATCH----------");
  console.log(match);
  console.log("-----------UNMATCH----------");
  console.log(unmatch);

  return {
    match: match,
    unmatch: unmatch,
  };
}

searchAndDivide("Lord");

/* EXERCISE 20

Write a function called "removeIndex" which receives a number as a parameter and returns the provided movies array without the element in the given position.

*/

titleCreator("EXERCISE 20", "---");

function removeIndex(number) {
  movies.splice(number, 1);
  return movies;
}

console.log(removeIndex(0));

// [EXTRAS] JS Advanced

titleCreator("JAVASCRIPT ADVANCED", "---");

/* EXERCISE 21

Create a function called "halfTree" which receives a number as a parameter and builds an "*" half tree with the given height.

Example:

halfTree(3)

*

**

***

*/

titleCreator("EXERCISE 21", "---");

function halfTree(number) {
  let stars = "";
  for (i = 0; i < number; i++) {
    // loop for new line
    for (j = 0; j <= i; j++) {
      // loop for stars -> 1. loop 1 star, 2. loop 2 stars...
      stars += "*";
    }
    stars += "\n";
  }
  console.log(stars);
}

halfTree(5);

/* EXERCISE 22

Create a function called "tree" which receives a number as a parameter and builds an "*" tree with the given height.

Example:

tree(3)

*

***

*****

*/

titleCreator("EXERCISE 22", "---");

function tree(number) {
  let string = "";
  for (i = 0; i < number; i++) {
    // loop for new line
    for (j = 0; j < number - i - 1; j++) {
      // loop for space ->
      string += " ";
    }
    for (let k = 0; k < 2 * i - 1; k++) {
      // loop for stars -> 1 stars, 3 stars, 5 stars...
      string += "*";
    }
    string += "\n";
  }
  console.log(string);
}

tree(7);

/* EXERCISE 23

Create a function called "isItPrime" that receives a number as a parameter and returns true if the given number is a prime number.

*/

titleCreator("EXERCISE 23", "---");

function isItPrime(number) {}

/* WHEN YOU ARE FINISHED

Commit and push the code to your personal GitHub repository; then post the link of your commit on the Homework section of today’s Eduflow.

*/
